ServerTokens Prod
ServerSignature Off
ServerName localhost

<DirectoryMatch "^/.*/\.">
    Require all denied
</DirectoryMatch>

<FilesMatch "^\.">
    Require all denied
</FilesMatch>

<DirectoryMatch "^/.*/@eaDir($|/)">
    Require all denied
</DirectoryMatch>

RedirectMatch 404 "(^|/)\.(?!well-known/)"
RedirectMatch 404 "(^|/)@eaDir($|/)"
